src/Entity/Agence.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgenceRepository")
 */
class Agence
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matriculeFiscale;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    private $nom;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Utilisateur", mappedBy="agence", cascade={"persist", "remove"})
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Terrain", mappedBy="agence", orphanRemoval=true)
     */
    private $terrains;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $num_tel;

    public function __construct()
    {
        $this->terrains = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatriculeFiscale(): ?string
    {
        return $this->matriculeFiscale;
    }

    public function setMatriculeFiscale(string $matriculeFiscale): self
    {
        $this->matriculeFiscale = $matriculeFiscale;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        // set (or unset) the owning side of the relation if necessary
        $newAgence = $utilisateur === null ? null : $this;
        if ($newAgence !== $utilisateur->getAgence()) {
            $utilisateur->setAgence($newAgence);
        }

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(?string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return Collection|Terrain[]
     */
    public function getTerrains(): Collection
    {
        return $this->terrains;
    }

    public function addTerrain(Terrain $terrain): self
    {
        if (!$this->terrains->contains($terrain)) {
            $this->terrains[] = $terrain;
            $terrain->setAgence($this);
        }

        return $this;
    }

    public function removeTerrain(Terrain $terrain): self
    {
        if ($this->terrains->contains($terrain)) {
            $this->terrains->removeElement($terrain);
            // set the owning side to null (unless already changed)
            if ($terrain->getAgence() === $this) {
                $terrain->setAgence(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return $this->nom;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(?string $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

}

src/Entity/Terrain.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TerrainRepository")
 */
class Terrain
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="float")
     */
    private $Largeur;

    /**
     * @ORM\Column(type="float")
     */
    private $Longueur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Agence", inversedBy="terrains")
     * @ORM\JoinColumn(nullable=false)
     */
    private $agence;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="terrain", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="terrain", orphanRemoval=true)
     */
    private $notes;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLargeur(): ?float
    {
        return $this->Largeur;
    }

    public function setLargeur(float $Largeur): self
    {
        $this->Largeur = $Largeur;

        return $this;
    }

    public function getLongueur(): ?float
    {
        return $this->Longueur;
    }

    public function setLongueur(float $Longueur): self
    {
        $this->Longueur = $Longueur;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getAgence(): ?agence
    {
        return $this->agence;
    }

    public function setAgence(?agence $agence): self
    {
        $this->agence = $agence;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setTerrain($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getTerrain() === $this) {
                $reservation->setTerrain(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setTerrain($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getTerrain() === $this) {
                $note->setTerrain(null);
            }
        }

        return $this;
    }


    public function getNoteStade(): ?float
    {
        
        $notesStade=$this->notes;
        $i=0;
        $j=0;
        foreach ($notesStade as $value){
         $j=$j+1;
         $i=$i+$value;   
        }
        if($j==0)
        {
            return 0;

        }
        else
        {
            return $i/$j;

        }
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/EspaceClientController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Terrain;
use App\Entity\Reservation;
use App\Entity\Agence;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;

class EspaceClientController extends AbstractController
{
    /**
     * @Route("/espace_client", name="espace_client") 
     */

    public function index()
    {
        $user = $this->getUser();
        return $this->render('espace_client/index.html.twig', [
            'controller_name' => 'EspaceClientController','utilisateur'=>$user
        ]);
    }

    /**
     * @Route("/espace_client/reservation/{id}", name="espace_client_reservation")
     */

    public function reservation($id,Request $request,EntityManagerInterface $manager)
    {
        
        $terrain = $this->getDoctrine()
        ->getRepository(Terrain::class)
        ->find($id);
        
        $agence=$terrain->getAgence();
        if ($request->isMethod('post')) 
        {
            
            $date=$request->request->get('date');
            $heure=$request->request->get('heure');
            $dateh = new \DateTime($date.' '.$heure.':00:00');
            
            $reservation=new Reservation();
            
            $reservation->setDate($dateh)
                        ->setStatus('wait')
                        ->setTerrain($terrain)
                        ->setClient( $this->getUser()->getClient());
            $manager->persist($reservation);
            $manager->flush(); 
            return $this->render('espace_client/reservation.html.twig', [
                'terrain' => $terrain,'agence'=>$agence,'notification' => 'success','contenu'=>'Demande De Reservation effectuee' 
            ]);
          
        }
        else
        {

            return $this->render('espace_client/reservation.html.twig', [
                'terrain' => $terrain,'agence'=>$agence
            ]);
        }

    }
    /**
     * @Route("/espace_client/modifier_photo", name="espace_client_modifier_photo")
     */
    public function modifier_photo(Request $request)
    {
        if($request->isMethod('post'))
        {
            $client=$this->getUser()->getClient();

            $file = $request->files->get('photo');
            
            $fileName = md5(uniqid()).'.'.$file->guessExtension();
            $file->move($this->getParameter('upload_directory'),$fileName);
            $client->setPhoto($fileName);
            $this->getDoctrine()->getManager()->flush();   
                

            return $this->render('espace_client/modifier_photo.html.twig',array('notification' => 'success','contenu'=>'modification terminée avec succès' ));
          
        }
        else
        {
            return $this->render('espace_client/modifier_photo.html.twig', [
                'controller_name' => 'EspaceAgenceController',
            ]);
        }
       
    }



        /**
     * @Route("/espace_client/mes_reservation", name="espace_client_mes_reservation")
     */
    public function mes_reservation(Request $request)
    {
            $entityManager = $this->getDoctrine()->getManager();
            $client = $this->getUser()->getClient();
        
            
            $req=" SELECT r FROM App\Entity\Reservation r where r.client= :client ";
            $query = $entityManager->createQuery($req)->setParameters(array('client'=>$client));
                

            $reservations= $query->execute();

            return $this->render('espace_client/mes_reservation.html.twig', [
                'reservations' => $reservations,
            ]);
    }



     /**
     * @Route("/espace_client/nos_agences", name="espace_client_nos_agences")
     */
    public function nos_agences(Request $request)
    {

        
        if ($request->isMethod('post')) {
            
            $entityManager = $this->getDoctrine()->getManager();
            $nom=$request->request->get('nom');
            $req='';
            if($nom != NULL )
            {
                $req=" SELECT p FROM App\Entity\Agence p WHERE  p.nom LIKE :nom ";
                $query = $entityManager->createQuery($req)->setParameters(array('nom'=> '%'.$nom.'%'));
            }
            else
            {
                
                $req=" SELECT p FROM App\Entity\Agence p  ";
                $query = $entityManager->createQuery($req);
            }

            $agence= $query->execute();
        }
        else
        {
            
        $repository = $this->getDoctrine()->getRepository(Agence::class);
        $agence = $repository->findAll();
        }        
        
        return $this->render('espace_client/nos_agences.html.twig', [
            'agences' => $agence,
        ]);
    }




      /**
     * @Route("/espace_client/nos_terrains", name="espace_client_nos_terrains")
     */
    public function nos_terrains(Request $request)
    {

        if ($request->isMethod('post')) {
            
            $entityManager = $this->getDoctrine()->getManager();
            $nom=$request->request->get('nom');
            $categorie=$request->request->get('categorie');
            $req='';
            if($nom != NULL &&  $categorie!= NULL)
            {
            $req=" SELECT p FROM App\Entity\Terrain p WHERE  p.nom LIKE :nom AND p.categorie LIKE :categorie ";
            $query = $entityManager->createQuery($req)->setParameters(array('nom'=> '%'.$nom.'%', 'categorie' => $categorie));
            }
            elseif($nom != NULL &&  $categorie== NULL)
            {
                $req=" SELECT p FROM App\Entity\Terrain p WHERE  p.nom LIKE :nom ";
                $query = $entityManager->createQuery($req)->setParameters(array('nom'=> '%'.$nom.'%'));
            }
            
            elseif($nom == NULL &&  $categorie!= NULL)
            {
                $req=" SELECT p FROM App\Entity\Terrain p WHERE  p.categorie LIKE :categorie ";
                $query = $entityManager->createQuery($req)->setParameters(array('categorie' => $categorie));
            }
            else
            {
                
                $req=" SELECT p FROM App\Entity\Terrain p  ";
                $query = $entityManager->createQuery($req);
            }



            $terrain= $query->execute();
        }
        else
        {
            $repository = $this->getDoctrine()->getRepository(Terrain::class);
            $terrain = $repository->findAll();
        }        
        return $this->render('espace_client/nos_terrains.html.twig', [
            'terrains' => $terrain,
        ]);
    }


}

templates/espace_client/index.html.twig
{% extends 'espace_client_base.html.twig' %}

{% block title %}Hello EspaceClientController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/DELL/Desktop/GOAL/GOAL/src/Controller/EspaceClientController.php'|file_link(0) }}">src/Controller/EspaceClientController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/DELL/Desktop/GOAL/GOAL/templates/espace_client/index.html.twig'|file_link(0) }}">templates/espace_client/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/espace_client/mes_reservation.html.twig
{% extends 'espace_client_base.html.twig' %}

{% block title %} Inscription Agence{% endblock %}

{% block body_notification %}

{% if notification is defined %} onload="setTimeout(cacherDiv,6000);" {% endif %}

{% endblock %}




{% block section %}


{% if notification is defined %} 


<div id="notification">
                <div class="rectangle {{notification}}">
                    <div class="notification-text">
                        <img src="/images/icone/{{notification}}.svg" id="icone_notification">
                        <span>{{contenu | raw}}</span>
                    </div>
                </div>
            </div>
       

 {% endif %}




    <h1>Demande De Réservation</h1>
           
     <article>  
      
                    <table>



              <tr  class="titre_tab"><td>
              Identifiant De Réservation </td>
              <td>
              Date De Réservation </td>
              <td>
              Nom Du Agence </td>
              <td>
              Nom Du Stade  </td>
              
              <td>
              Categorie Du Stade  </td>
              
              <td>
              Status De Réservation  </td>
              
             
              </tr>
            {% set j = 0 %}
             {% for reservation in reservations %}
               
            
            {% if j is divisible by(2) %}
                <tr class="impaire">
            {% else %}
                <tr class="paire">
            
            {% endif %}
                <td>
              {{reservation.id}} </td>
                      <td>
              {{reservation.date|date("Y-d-m H:i")}} </td>
              <td>
               {{reservation.terrain.agence.nom}}  </td>
              <td>
             
                {{reservation.terrain.nom}} </td>
              <td>

              
                {{reservation.terrain.categorie}} </td>
              <td>
             
                {{reservation.Status}} </td>
                </tr>
            {% set j = j + 1 %}
    
              
             {% endfor %}
          </table>
    
      
      
    </article>
    
{% endblock %}

templates/espace_client/nos_agences.html.twig
{% extends 'espace_client_base.html.twig' %}

{% block title %} Nos Agences{% endblock %}

{% block section %}

   <article>  
      
    
<div class="slideshow-container">


    <div class="myslides fade">
    
    <div class="numbers">1 / 4</div>
    
    <div><img src="/images/photo/agence1.jpg" alt="Exemple de stade de basket."class="slider_img"></div>
    
  
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">2 / 4</div>
    
    <div><img src="/images/photo/agence2.jpg" alt="Exemple de stade de tennis." class="slider_img"></div>
    
    
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">3 / 4</div>
    
    <div><img src="/images/photo/agence3.jpg" alt="Exemple de stade de foot." class="slider_img"></div>
    
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">4 / 4</div>
    
    <div><img src="/images/photo/agence4.jpg" alt="Exemple de stade de tennis." class="slider_img"></div>
    
    
    
    </div>
    
    
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
    
    
    </div>
    
    <br>
    
    
    <div style="text-align:center">
    
    <span class="dots" onclick="currentSlide(1)"></span> 
    
    <span class="dots" onclick="currentSlide(2)"></span> 
    
    <span class="dots" onclick="currentSlide(3)"></span> 
    
    <span class="dots" onclick="currentSlide(4)"></span> 
    
    </div>

</article>
<article>
<form method='post' action="{{path('espace_client_nos_agences')}}">
<div class="rechercheterrain">





                  <button type="submit" class="bouton_recherche"><img src="/images/icone/loupe_inv.svg"></button>
  
                  <div class="floating-label">      
                
                    <input class="floating-input" type="text" placeholder=" " name="nom">
                
                    <span class="highlight"></span>
                
                    <label>Nom Agence</label>
                
                </div>

                <div class="floating-label">  
                
                    <select class="floating-select" onclick="this.setAttribute('value', this.value);" value="" name="trier">
                
                        <option value=""></option>
                
                        
                        <option value="distance">Distance</option>
                
                        <option value="note">Note</option>
                
               
                    </select>
                
               
                    <span class="highlight"></span>
               
                    
                
                    <label>Trier</label>
                
                
                </div>




</div>
</form>

</article>



<article>







      
      {% set j = 0 %}

      {% for agence in agences %}
        
      {% set j = j + 1 %}



      
      <div id="{{agence.id}}" class="overlay">
        <div class="popup">
          <div class="close">
            <a href="#stade{{agence.id}}">&times;</a>
          </div>
          <div class="content">
            <center>
                <a href="/images/photo/{{agence.photo}}"><img src="/images/photo/{{agence.photo}}" class="modalphoto"></a>
          </center>
  
          <table>
              <tr class="paire"><td><span class="champ">Nom : </span>         {{agence.nom}}</td>
              </tr>
  
              <tr class="impaire"><td><span class="champ">Numero Téléphone : </span>        {{agence.numTel}}</td>
              </tr>
              
  
            </table>
  
  
          </div>
        </div>
      </div>




{% endfor %}




 <div class="stades">
      {% set i = 0 %}
      
      {% for agence in agences %}

        {% if i == 0 %}
            <div class="stades">
        {% endif %}


          <div class="stade">
            
              <a href="#{{agence.id}}" id="stade{{agence.id}}">
                  <img src="/images/photo/{{agence.photo}}">
                  <span class="note_stade"><span class="star">&#9733;</span>4.3</span>
                  
                  <span class="titre_stade">{{agence.nom}}</span>
                  </a>
          </div>
        
        
        
        
        {% set i = i + 1 %}

        {% if i != j and i is divisible by(4) %}
            </div>
            <div class="stades">
        {% endif %}  
            
        {% if i == j %}
            </div>
        {% endif %}

      {% endfor %}


 




</article>

{% endblock %}

templates/espace_client/nos_terrains.html.twig
{% extends 'espace_client_base.html.twig' %}

{% block title %} Nos Terrain{% endblock %}

{% block section %}

   <article>  
      
    
<div class="slideshow-container">


    <div class="myslides fade">
    
    <div class="numbers">1 / 4</div>
    
    <div><img src="/images/photo/basketball1.jpg" alt="Exemple de stade de basket."class="slider_img"></div>
    
  
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">2 / 4</div>
    
    <div><img src="/images/photo/tennis2.jpg" alt="Exemple de stade de tennis." class="slider_img"></div>
    
    
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">3 / 4</div>
    
    <div><img src="/images/photo/football.jpg" alt="Exemple de stade de foot." class="slider_img"></div>
    
    
    </div>
    
    
    <div class="myslides fade">
    
    <div class="numbers">4 / 4</div>
    
    <div><img src="/images/photo/tennis3.jpg" alt="Exemple de stade de tennis." class="slider_img"></div>
    
    
    
    </div>
    
    
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
    
    
    </div>
    
    <br>
    
    
    <div style="text-align:center">
    
    <span class="dots" onclick="currentSlide(1)"></span> 
    
    <span class="dots" onclick="currentSlide(2)"></span> 
    
    <span class="dots" onclick="currentSlide(3)"></span> 
    
    <span class="dots" onclick="currentSlide(4)"></span> 
    
    </div>

</article>
<article>
<form method='post' action="{{path('espace_client_nos_terrains')}}">
<div class="rechercheterrain">





                  <button type="submit" class="bouton_recherche"><img src="/images/icone/loupe_inv.svg"></button>
  
                  <div class="floating-label">      
                
                    <input class="floating-input" type="text" placeholder=" " name="nom">
                
                    <span class="highlight"></span>
                
                    <label>Nom Terrain</label>
                
                </div>

                <div class="floating-label">  
                
                    <select class="floating-select" onclick="this.setAttribute('value', this.value);" value="" name="trier">
                
                        <option value=""></option>
                
                        
                        <option value="distance">Distance</option>
                
                        <option value="note">Note</option>
                
               
                    </select>
                
               
                    <span class="highlight"></span>
               
                    
                
                    <label>Trier</label>
                
                
                </div>


                <div class="floating-label">  
                
                    <select class="floating-select" onclick="this.setAttribute('value', this.value);" value="" name="categorie">
                
                        <option value=""></option>
                
                        
                        <option value="tennis">Tennis</option>
                
                        <option value="foot">Foot</option>
                
                        <option value="basket">Basket</option>
            
                
               
                    </select>
                
               
                    <span class="highlight"></span>
               
                    
                
                    <label>Type</label>
                
                
                </div>


</div>

</form>

</article>




<article>



{% set j = 0 %}

      {% for terrain in terrains %}
        
      {% set j = j + 1 %}



      
      <div id="{{terrain.id}}" class="overlay">
        <div class="popup">
          <div class="close">
            <a href="#stade{{terrain.id}}">&times;</a>
          </div>
          <div class="content">
            <center>
                <a href="/images/photo/{{terrain.photo}}"><img src="/images/photo/{{terrain.photo}}" class="modalphoto"></a>
          </center>
          {% set sumratings = 0 %}
          {% set i = 0 %}
          {% for rating in terrain.notes %}
            {% set sumratings = sumratings + rating.note %}  
            {% set i = i + 1 %}
          {% endfor %}
          <table>
              <tr class="paire"><td><span class="champ">Nom : </span>         {{terrain.nom}}</td>
              </tr>
  
              <tr class="impaire"><td><span class="champ">Largeur : </span>         {{terrain.largeur}}</td>
              </tr>
              <tr class="paire"><td><span class="champ">Longueur : </span>         {{terrain.longueur}}</td>
                </tr>
    
                <tr class="impaire"><td><span class="champ">Nom d'agence : </span>         {{terrain.agence}}</td>
                </tr>
                <tr class="paire"><td><span class="champ">Note : </span>           {% if i == 0 %}
                  --/5
                  {% else %}
                  
                  {{  sumratings / terrain.notes|length }}/5
                  {% endif %}</td>
                  </tr>
      
                  <tr class="impaire"> <td><span class="champ">Categorie : </span>         {{terrain.categorie}}</td>
                  </tr>
  
            </table>


             <center>
          <div>
          <a href="{{ path('espace_client_reservation', { 'id': terrain.id }) }}">
            <button  class="connection_bouton">Réservation</button>
            </a>
          </div></center>

         <div id="rating_sys">


          <span class="stars"><a href="{{path('espace_public_note',{'terrain': terrain.id, 'noteint': 1})}}" class="lienjs">&starf;</a></span>
          <span class="stars"><a href="{{path('espace_public_note',{'terrain': terrain.id, 'noteint': 2})}}" class="lienjs">&starf;</a></span>
          <span class="stars"><a href="{{path('espace_public_note',{'terrain': terrain.id, 'noteint': 3})}}" class="lienjs">&starf;</a></span>
          <span class="stars"><a href="{{path('espace_public_note',{'terrain': terrain.id, 'noteint': 4})}}" class="lienjs">&starf;</a></span>
          <span class="stars"><a href="{{path('espace_public_note',{'terrain': terrain.id, 'noteint': 5})}}" class="lienjs">&starf;</a></span>
         </div>

          
  
          </div>
        </div>
      </div>




{% endfor %}


      


      <div class="stades">
      {% set i = 0 %}
      
      {% for terrain in terrains %}

        {% if i == 0 %}
            <div class="stades">
        {% endif %}


          <div class="stade">
              {% set sumratings = 0 %}
              {% set i = 0 %}
              {% for rating in terrain.notes %}
                {% set sumratings = sumratings + rating.note %}  
                {% set i = i + 1 %}
              {% endfor %}
               

              <a href="#{{terrain.id}}" id="stade{{terrain.id}}">
                  <img src="/images/photo/{{terrain.photo}}">
                  <span class="note_stade"><span class="star">&#9733;</span>
                  {% if i == 0 %}
                  --
                  {% else %}
                  
                  {{  sumratings / terrain.notes|length }}
                  {% endif %}

                </span>
                  
                  <span class="titre_stade">{{terrain.nom}}</span>
                  </a>
          </div>
        
        
        
        
        {% set i = i + 1 %}

        {% if i != j and i is divisible by(4) %}
            </div>
            <div class="stades">
        {% endif %}  
            
        {% if i == j %}
            </div>
        {% endif %}

      {% endfor %}


 












</article>


{% endblock %}

{% block javascript %}
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>


  function onClickStar(event)
  {
    event.preventDefault();
    const url=this.href;
    axios.get(url).then(function(response){
     // document.getElementById(`stade${reponse.data.idTerrin}`);
      console.log(response)});
  }

  document.querySelectorAll( 'a.lienjs').forEach(function(link){
    link.addEventListener('click',onClickStar);
  })
</script>






{% endblock %}